= MALOL-Cancer

== Team M~oritz~A~rmin~L~inus~O~liver~L~uka~

Moritz Gruber, Armin Salkovic, Linus Nestler,  Oliver Daxinger, Luka Cvijic

== Documentation

=== Spezien

* Mensch
* Maus
* Fliege

=== Unsere gedachte Angabe


* Gen x (Mensch) verursacht im Menschen Krebs.
* Dieses wird an die DB geschickt. Die DB schaut ob es dieses Gen x in einem Tier gibt.
* Wenn ja, schaut man welche TierGenCombo {Gen x (im Tier) : Gen b} bei tieren die höchste Letalitätsrate hat.
* So hat man genpaare: {MausGen x ; MausGen b ; Lethality} -> Man schaut beim Tier-Human-Mapping Welches Gen im Mensch dem Gen MausGen b entspricht.

.Problem: Maus/Human Mapping haben 1:1 (Heißt Das Maus Gen ist Genau das Mensch Gen), aber 1 : n (Das MausGen sind mehrere Gene im Mensch)

* Dan hat man die Gene im Menschen die den Genen der Maus entsprechen, die das anfangs gen x auslöschen.
* Man muss noch schauen ob diese Menschen-Gene für den Mensch essenziell sind.
* Wenn nicht kann man annehmen das das Gen x im Menschen durch ein Gen (Das in der Maus eine Zelle auslöscht) auch im Menschen eine Zelle auslöscht.

=== IDs Mapping

Oma Seite:  entrez Gen Id(Mapping) stimmen mit den Id's HumanSl / FlySL / MouseSL überein
Aber nur manchmal nicht alle? Was ist das??

Essential Genes stimmt die locus id manchmal mit den SL ids überein also ned imma?

