@startuml
left to right direction

entity GenePairSL {
    * rStatisticScore
}

entity MappingData {
}

entity Gene {
    * Identifier
    --
    * Name
    * Essentiality
}

entity Species {
    * SpeciesId
    --
    * Name
}

Species "1"---"n" Gene
GenePairSL "n"---"2" Gene
MappingData "n"---"2" Gene

@enduml