@startuml
left to right direction

entity GenePairSL {
    * Gene1
    * Gene2
    --
    * rCellLine
    * rPubMedId
    * rSource
    * rStatisticScore
}

entity MappingData {
    * Gene1
    * Gene2
}

entity Gene {
    * Identifier
    --
    * Name
    * EssentialScore
}

entity Species {
    * SpeciesId
    --
    * Name
}

Species "1"---"n" Gene
GenePairSL "m"---"2" Gene
MappingData "1"---"2" Gene

@enduml